inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - ./config/initializers/inflections

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/**
    - lib/tasks/**
    - vendor/bundle/**/*
Style/AsciiComments:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Naming/AsciiIdentifiers:
  Enabled: false
Naming/MethodName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Naming/VariableName:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/factories/**/*'
RSpec/MultipleExpectations:
  Enabled: false
Rails/Output:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/ImplicitSubject:
  Enabled: false
