inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - ./config/initializers/inflections

AllCops:
  Exclude:
    - ./github/**/*
    - bin/**
    - db/schema.rb
    - db/migrate/**
    - lib/tasks/**
    - spec/factories/**/*
    - vendor/bundle/**/*

Metrics/AbcSize:
  Max: 25
Metrics/MethodLength:
  Max: 25
Metrics/BlockLength:
  Exclude:
    - 'spec/factories/**/*'
    - 'spec/**/*'

Style/AsciiComments:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/RescueStandardError:
  Exclude:
    - 'spec/**/*'
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
Lint/HandleExceptions:
  Exclude:
    - 'spec/**/*'

Naming/AsciiIdentifiers:
  Enabled: false
Naming/MethodName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Naming/VariableName:
  Enabled: false
Naming/BinaryOperatorParameterName:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
Rails/Output:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/ImplicitSubject:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/MessageChain:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
