inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - ./config/initializers/inflections

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/**
    - vendor/bundle/**/*
Style/AsciiComments:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false